advertisement/urls.py
from django.contrib import admin
from django.urls import path

from advertisement.views import AdvertisementDetail, AdvertisementList

urlpatterns = [
    path('', AdvertisementList.as_view(), name='advertisement_list'),
    path('detail/<int:pk>', AdvertisementDetail.as_view(), name='advertisement_detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('advertisement/', include('advertisement.urls'))
]

advertisement/models.py
from django.db import models


class Rubric(models.Model):
    title = models.CharField('заголовок', max_length=256)


class Advertisement(models.Model):
    title = models.CharField('заголовок', max_length=256)
    description = models.TextField('описание')
    price = models.IntegerField(default=0)
    rubric = models.ForeignKey(Rubric, on_delete=models.SET_NULL, null=True, blank=True)
    type = models.CharField(max_length=128, default='sell', choices=(
        ('sell', 'Продажа'),
        ('buy', 'Покупка')
    ))
    contact_info = models.TextField()
    view_count = models.IntegerField(default=0)

advertisement/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from advertisement.models import Advertisement


class AdvertisementList(ListView):
    model = Advertisement
    template_name = 'advertisement/list.html'


class AdvertisementDetail(DetailView):
    model = Advertisement
    template_name = 'advertisement/detail.html'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        self.object.view_count += 1
        self.object.save()
        return response

advertisement/templates/advertisement/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    <li>Заголовок: {{ advertisement.title }}</li>
    <li>Цена: {{ advertisement.price }} руб.</li>
    <li>Описание: {{ advertisement.description }}</li>
    <li>Рубрика: {{ advertisement.rubric.title }}</li>
    <li>Тип: {{ advertisement.get_type_display }}</li>
    <li>Контакт: {{ advertisement.contact_info }}</li>
    <li>Кол-во просмотров: {{ advertisement.view_count }}</li>
</ul>
</body>
</html>

advertisement/templates/advertisement/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<ul>
    {% for advertisement in advertisement_list %}
        <li>
            <a href="{% url 'advertisement_detail' pk=advertisement.pk %}">{{ advertisement.title }}</a>
            | {{ advertisement.price }} руб. | {{ advertisement.rubric.title }}
        </li>
    {% endfor %}

</ul>

</body>
</html>